<?php

namespace ContainerYrBKLlv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1IC0rxZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1IC0rxZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1IC0rxZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'weatherService' => ['privates', 'App\\Service\\WeatherService', NULL, 'Cannot autowire service "App\\Service\\WeatherService": argument "$apiUrl" of method "__construct()" is type-hinted "string", you should configure its value explicitly.'],
        ], [
            'weatherService' => 'App\\Service\\WeatherService',
        ]);
    }
}
