<?php

namespace Container0ZxJEyw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWeatherControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\WeatherController' shared autowired service.
     *
     * @return \App\Controller\WeatherController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\WeatherController'] = $instance = new \App\Controller\WeatherController();

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\WeatherController', $container));

        return $instance;
    }
}
