<?php

namespace ContainerXZv8dYF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2T9q3iZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2T9q3iZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2T9q3iZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'locationService' => ['privates', 'App\\Service\\LocationService', 'getLocationServiceService', true],
        ], [
            'locationService' => 'App\\Service\\LocationService',
        ]);
    }
}
