<?php

namespace ContainerXZv8dYF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6Cad0S9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6Cad0S9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6Cad0S9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['privates', '.errored.eBZFxJ2', NULL, 'Cannot determine controller argument for "App\\Controller\\HomeController::new()": the $doctrine argument is type-hinted with the non-existent class or interface: "Doctrine\\Common\\Persistence\\ManagerRegistry".'],
            'tweetsRepository' => ['privates', 'App\\Repository\\TweetsRepository', 'getTweetsRepositoryService', true],
        ], [
            'doctrine' => '?',
            'tweetsRepository' => 'App\\Repository\\TweetsRepository',
        ]);
    }
}
