<?php

namespace ContainerXZv8dYF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9ebkeD1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9ebkeD1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9ebkeD1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.dkAX.gh', 'get_ServiceLocator_DkAX_GhService', true],
            'App\\Controller\\HomeController::new' => ['privates', '.service_locator.6Cad0S9', 'get_ServiceLocator_6Cad0S9Service', true],
            'App\\Controller\\LocationController::index' => ['privates', '.service_locator.2T9q3iZ', 'get_ServiceLocator_2T9q3iZService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\WeatherController2::index' => ['privates', '.service_locator.1IC0rxZ', 'get_ServiceLocator_1IC0rxZService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.dkAX.gh', 'get_ServiceLocator_DkAX_GhService', true],
            'App\\Controller\\HomeController:new' => ['privates', '.service_locator.6Cad0S9', 'get_ServiceLocator_6Cad0S9Service', true],
            'App\\Controller\\LocationController:index' => ['privates', '.service_locator.2T9q3iZ', 'get_ServiceLocator_2T9q3iZService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\WeatherController2:index' => ['privates', '.service_locator.1IC0rxZ', 'get_ServiceLocator_1IC0rxZService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\HomeController::new' => '?',
            'App\\Controller\\LocationController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\WeatherController2::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\HomeController:new' => '?',
            'App\\Controller\\LocationController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\WeatherController2:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
