<?php

namespace ContainerXZv8dYF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_EBZFxJ2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.eBZFxJ2' shared service.
     *
     * @return \Doctrine\Common\Persistence\ManagerRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\HomeController::new()": the $doctrine argument is type-hinted with the non-existent class or interface: "Doctrine\\Common\\Persistence\\ManagerRegistry".');
    }
}
