<?php

namespace ContainerXZv8dYF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\LocationService' shared autowired service.
     *
     * @return \App\Service\LocationService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\LocationService'] = new \App\Service\LocationService();
    }
}
