<?php

namespace ContainerHoUq1ps;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormTweetTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\FormTweetType' shared autowired service.
     *
     * @return \App\Form\FormTweetType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\FormTweetType'] = new \App\Form\FormTweetType();
    }
}
