<?php

namespace ContainerLEXacuR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWeatherServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\WeatherService' shared autowired service.
     *
     * @return \App\Service\WeatherService
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\Service\\WeatherService": argument "$apiUrl" of method "__construct()" is type-hinted "string", you should configure its value explicitly.');
    }
}
