<?php

namespace ContainerPThU0wa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubscribeRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\SubscribeRepository' shared autowired service.
     *
     * @return \App\Repository\SubscribeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SubscribeRepository'] = new \App\Repository\SubscribeRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
