<?php

namespace ContainerPThU0wa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTweetsTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\TweetsType' shared autowired service.
     *
     * @return \App\Form\TweetsType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\TweetsType'] = new \App\Form\TweetsType();
    }
}
