<?php

namespace ContainerK16VoRU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3JHlvRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3JHlv_r' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3JHlv_r'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'FormTweet' => ['privates', 'App\\Form\\FormTweetType', 'getFormTweetTypeService', true],
            'TweetsRepository' => ['privates', 'App\\Repository\\TweetsRepository', 'getTweetsRepositoryService', true],
        ], [
            'FormTweet' => 'App\\Form\\FormTweetType',
            'TweetsRepository' => 'App\\Repository\\TweetsRepository',
        ]);
    }
}
