<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPThU0wa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPThU0wa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPThU0wa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPThU0wa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPThU0wa\App_KernelDevDebugContainer([
    'container.build_hash' => 'PThU0wa',
    'container.build_id' => 'c918091e',
    'container.build_time' => 1677245498,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPThU0wa');
