<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHRHDVcB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHRHDVcB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHRHDVcB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHRHDVcB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHRHDVcB\App_KernelDevDebugContainer([
    'container.build_hash' => 'HRHDVcB',
    'container.build_id' => 'fb2c6086',
    'container.build_time' => 1677249895,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHRHDVcB');
