<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0ZxJEyw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0ZxJEyw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0ZxJEyw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0ZxJEyw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0ZxJEyw\App_KernelDevDebugContainer([
    'container.build_hash' => '0ZxJEyw',
    'container.build_id' => 'ae8211c5',
    'container.build_time' => 1672843268,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0ZxJEyw');
