<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.d5b2777f.js',
                '/build/360.18e0dfea.js',
                '/build/app.00b2400f.js',
            ],
            'css' => [
                '/build/app.c85c8e3c.css',
            ],
        ],
    ],
],

]];
