<?php

namespace ContainerLM4Xl9b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTweetsRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\TweetsRepository' shared autowired service.
     *
     * @return \App\Repository\TweetsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\TweetsRepository'] = new \App\Repository\TweetsRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
